require 'rake/testtask'
require 'rubygems/package_task'


spec = eval(File.read('<%= name %>.gemspec'))

Gem::PackageTask.new(spec) do |p|
  p.gem_spec = spec
end

desc 'Release to rubygems'
task release: :package do
  require 'rake/gemcutter'
  Rake::Gemcutter::Tasks.new(spec).define
  Rake::Task['gem:push'].invoke
end
